
import React from 'react';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { motion } from "framer-motion";

const ResourceFAQs = () => {
  const faqs = [
    {
      question: "What is a carbon footprint?",
      answer: "A carbon footprint is the total amount of greenhouse gases (primarily carbon dioxide) that are generated by our actions. It includes both direct emissions, such as those from driving a car or using electricity, and indirect emissions from the production and transportation of the goods we consume."
    },
    {
      question: "Why is reducing my carbon footprint important?",
      answer: "Reducing your carbon footprint helps mitigate climate change by limiting greenhouse gas emissions that trap heat in the atmosphere. Individual actions, when taken collectively, can make a significant impact. Additionally, many carbon-reducing actions also save money, improve health, and enhance quality of life."
    },
    {
      question: "How accurate is the carbon calculator?",
      answer: "Our calculator provides a good estimate based on the information you provide. It uses scientifically validated emission factors and methodologies. However, like all calculators, it relies on averages and assumptions. For the most accurate results, provide detailed information and update your profile regularly as your habits change."
    },
    {
      question: "What's the difference between carbon neutral and net-zero?",
      answer: "Carbon neutral means balancing carbon emissions with carbon removal or offset purchases. Net-zero is more comprehensive, requiring deep emissions reductions across your entire carbon footprint, with any remaining emissions balanced by carbon removals. Net-zero is generally considered more rigorous and aligned with global climate goals."
    },
    {
      question: "How often should I calculate my carbon footprint?",
      answer: "We recommend recalculating your footprint every 3-6 months, or whenever you make significant lifestyle changes that would affect your emissions (like moving, changing jobs, or buying a new vehicle). Regular recalculation helps you track progress and stay motivated."
    },
    {
      question: "What are the most effective ways to reduce my carbon footprint?",
      answer: "The highest-impact actions typically include: reducing air travel, shifting to a more plant-based diet, driving less (or switching to an electric vehicle), improving home energy efficiency, and reducing consumption of new goods. Our personalized recommendations will help you identify the most effective actions for your specific situation."
    },
    {
      question: "Are carbon offsets a good solution?",
      answer: "Carbon offsets can be part of a comprehensive approach to addressing climate change, but they should not be the first or only strategy. We recommend following a hierarchy: first measure your emissions, then reduce them as much as possible, and finally offset what you cannot reduce. When purchasing offsets, choose high-quality, verified projects."
    },
    {
      question: "How do I compare to the average person?",
      answer: "The global average carbon footprint is approximately 4-5 tons CO₂e per person annually, but this varies significantly by country. In the U.S., the average is about 16 tons per person, while in India it's around 1.9 tons. For context, to meet global climate goals, we need to reach about 2 tons per person by 2050."
    }
  ];

  return (
    <div>
      <h2 className="text-2xl font-bold mb-6">Frequently Asked Questions</h2>
      
      <div className="grid grid-cols-1 gap-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <Card>
            <CardHeader>
              <CardTitle>Common Questions About Carbon Footprints</CardTitle>
              <CardDescription>Find answers to the most frequently asked questions about carbon emissions and sustainability</CardDescription>
            </CardHeader>
            <CardContent>
              <Accordion type="single" collapsible className="w-full">
                {faqs.map((faq, index) => (
                  <AccordionItem key={index} value={`item-${index}`}>
                    <AccordionTrigger className="text-left hover:no-underline hover:text-carbon-600 font-medium">
                      {faq.question}
                    </AccordionTrigger>
                    <AccordionContent className="text-gray-600">
                      {faq.answer}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </div>
  );
};

export default ResourceFAQs;
